owner: froggie3
repo: upptime
user-agent: UpptimeBot (https://github.com/froggie3/upptime)

sites:
  - name: yokkin.com
    url: https://yokkin.com
  - name: iigau lab
    url: https://akkoma.yokkin.com
  - name: Gitea
    url: https://git.yokkin.com
  - name: Nextcloud
    url: https://nextcloud.yokkin.com
  - name: sanctunes
    url: https://sanctunes.yokkin.com
